/** Seed values for managed reference lists (BRD Section 10). */

export const REFERENCE_LISTS: Record<string, { label: string; values: string[] }> = {
  region: {
    label: "Region",
    values: ["Carolinas", "Central", "Florida", "Georgia", "Texas"],
  },
  preconDepartment: {
    label: "Precon Department",
    values: [
      "Carolinas",
      "Central Building Group",
      "Central Federal",
      "Central Heavy Civil",
      "Central Nashville",
      "Florida",
      "Georgia – Commercial",
      "Georgia – Healthcare",
      "Georgia – Mission Critical & Industrial",
      "Texas",
    ],
  },
  estimatePhase: {
    label: "Estimate Phase",
    values: [
      "Budget – Quick ROM",
      "Budget – Concept",
      "Budget – SD",
      "Budget – DD",
      "Budget – Early Release",
      "Early Release",
      "GMP",
      "Hard Bid/Firm Fixed",
      "Rates Only",
      "Qualifications Only",
      "Reconciliation",
      "Value Engineering",
    ],
  },
  contractType: {
    label: "Contract Type",
    values: [
      "GC – Cost Plus",
      "GC – Cost Plus w/GMP",
      "GC – Lump Sum",
      "DB – Cost Plus",
      "DB – Cost Plus w/GMP",
      "DB – Lump Sum",
      "Unit Price",
      "Program Manager",
      "IPD/Multi-Party",
      "ECI",
      "Other",
    ],
  },
  mlt: {
    label: "Market Leadership Team (MLT)",
    values: [
      "Commercial",
      "Federal",
      "Healthcare",
      "Heavy Civil",
      "Industrial",
      "Mission Critical",
    ],
  },
  marketSector: {
    label: "Market Sector",
    values: [
      "Aerospace – Manufacturing",
      "Aerospace – MRO",
      "Commercial – Office",
      "Commercial – Mixed Use",
      "Commercial – Retail",
      "Commercial – Warehouse/Distribution",
      "Education – Higher Ed",
      "Education – K-12",
      "Energy – Power Generation",
      "Energy – Renewables",
      "Energy – Transmission",
      "Government – Federal",
      "Government – State/Local",
      "Government – Military",
      "Healthcare – Hospital",
      "Healthcare – Medical Office",
      "Healthcare – Ambulatory/Surgery",
      "Healthcare – Behavioral",
      "Hospitality – Hotel",
      "Hospitality – Resort",
      "Industrial – Automotive",
      "Industrial – Food & Beverage",
      "Industrial – Manufacturing",
      "Industrial – Pharmaceutical",
      "Infrastructure – Bridges",
      "Infrastructure – Highways",
      "Infrastructure – Water/Wastewater",
      "Infrastructure – Dams & Locks",
      "Mission Critical – Data Center",
      "Mission Critical – Network",
      "Multi-Family – Apartments",
      "Multi-Family – Condominiums",
      "Multi-Family – Student Housing",
      "Science & Tech – Lab/Research",
      "Science & Tech – Cleanroom",
      "Senior Living – Assisted",
      "Senior Living – Independent",
      "Sports & Entertainment – Stadium",
      "Sports & Entertainment – Arena",
      "Sports & Entertainment – Performing Arts",
    ],
  },
  procurement: {
    label: "Procurement",
    values: ["RFP/RFQ", "Bid – Closed", "Bid – Open", "Bid – Best Value", "Negotiated"],
  },
  designContract: {
    label: "Design/Contract",
    values: ["Bid-Build", "Design Build", "Hybrid DB"],
  },
  internalJointVenture: {
    label: "Internal Joint Venture",
    values: ["None", "IJV – Cross Division", "IJV – Cross Region"],
  },
  awardability: {
    label: "Awardability",
    values: [
      "Work Under Contract – Hard Bid",
      "Work Under Contract – GMP",
      "Work Under Contract – Early Release",
      "Not Work Under Contract – Budget",
      "Not Work Under Contract – Other",
    ],
  },
  statusAtPricing: {
    label: "Status at Pricing",
    values: ["Prospective", "Committed", "Work Under Contract"],
  },
  selfPerformWorkType: {
    label: "Self-Perform Work Type",
    values: [
      "Sitework – Earthwork",
      "Sitework – Utilities",
      "Sitework – Paving",
      "Concrete – Foundations",
      "Concrete – Structural",
      "Concrete – Flatwork",
      "Concrete – Tilt-Up",
      "Masonry – Block",
      "Masonry – Brick",
      "Erection – Structural Steel",
      "Erection – Precast",
      "Interior Finishes – Drywall",
      "Interior Finishes – Doors/Hardware",
      "Interior Finishes – Specialties",
      "Marine – Dredging",
      "Marine – Pile Driving",
      "Process Piping",
      "Process Equipment Setting",
      "Demolition",
      "Rough Carpentry",
    ],
  },
  equipmentRates: {
    label: "Equipment Rates",
    values: ["Market", "BGES Strategic", "R5 Strategic", "Bluebook"],
  },
  supportGroups: {
    label: "Support Groups",
    values: [
      "VDC",
      "Design Management",
      "Scheduling",
      "Construction Engineering",
      "Self Perform Support",
      "Supplier Opportunity",
      "MLT Support",
      "Procurement",
      "MEP",
      "Safety",
    ],
  },
  bidYear: {
    label: "Bid Year",
    values: Array.from({ length: 11 }, (_, i) => String(2024 + i)),
  },
  projectPlanningPreconEngagement: {
    label: "Project Planning Precon Engagement",
    values: ["Full Precon", "Partial Precon", "Bid Only", "None"],
  },
  businessStrategyValues: {
    label: "Business Strategy Values",
    values: [
      "Core Market Growth",
      "New Market Entry",
      "Key Client Relationship",
      "Self-Perform Leverage",
      "Backlog Fill",
      "Strategic Pursuit",
    ],
  },
};
